HR_QUESTIONS = [
    "Tell me about yourself.",
    "Why should we hire you?",
    "What are your greatest strengths?",
    "What is your biggest weakness?",
    "Where do you see yourself in five years?",
    "Why do you want to work for our company?",
    "Why are you interested in this role?",
    "What motivates you to perform well at work?",
    "Describe a challenge you faced and how you overcame it.",
    "Tell me about a time you failed and what you learned from it.",
    "Describe a situation where you had to work under pressure.",
    "How do you prioritize tasks when multiple deadlines are approaching?",
    "Tell me about a time when you had to learn a new skill quickly.",
    "Describe a difficult decision you had to make.",
    "Have you ever disagreed with a teammate? How did you handle it?",
    "Tell me about a conflict in a team and how you resolved it.",
    "Describe a time when you helped a teammate.",
    "How do you handle criticism and feedback?",
    "Tell me about a time you received negative feedback.",
    "Describe a situation where you showed leadership.",
    "Tell me about a time you took initiative without being asked.",
    "How do you handle repetitive tasks?",
    "What does teamwork mean to you?",
    "Describe your ideal work environment.",
    "How do you manage your time effectively?",
    "What would your friends or classmates say about you?",
    "Why did you choose Computer Science/IT?",
    "What projects are you most proud of?",
    "Tell me about your final year project.",
    "What role did you play in your team projects?",
    "How do you stay updated with new technologies?",
    "Tell me about a time you had to solve a problem creatively.",
    "How do you deal with tight deadlines?",
    "What would you do if you were assigned a task you had never done before?",
    "How do you ensure accuracy in your work?",
    "Tell me about a time when you made a mistake.",
    "How would you handle an unhappy client or customer?",
    "What are your salary expectations?",
    "Why are you looking for a new opportunity?",
    "What are your career goals?",
    "What do you know about our company?",
    "What makes you different from other candidates?",
    "Describe a time when you had to adapt to change.",
    "How do you handle stress during important projects?",
    "What is your biggest professional achievement?",
    "Are you comfortable working independently and in a team?",
    "How would you handle a situation where your manager disagrees with you?",
    "What would you do if you missed an important deadline?",
    "Do you have any questions for us?",
    "Why should we select you over other applicants?"
]